
== maugitea
A Gitea client and webhook receiver for maubot.

WARNING: This bot is still under development, so things may change, break, or even work properly.

Matrix room: #maugitea:saces.de

=== Install & Run

maugitea: just a regular plugin, zip it and upload it.

=== Webhooks

url: https://fancy.domain/_matrix/maubot/plugin/<instance_name>/webhook/r0?room=<room-id>

Add the secret to base-config.yaml

 webhook-secret: "your secret here"

Still a lot to do.

=== Bot usage

 Notation: command[abbr, aliases]

Any incomplete command should give help.

 !gitea

Ping the bot

 !gitea ping[p]

==== Server Alias

Note: the url have to be complete for the endpoint, something like 'https://your.git.ea/api/v1' 

 !gitea alias[a]
 !gitea alias add[a] <alias> <url>
 !gitea alias remove[r, rm] <alias>
 !gitea alias list[l, ls]

==== Server

 !gitea server[s]
 !gitea server list[ls]
 !gitea server login[l] <url or alias> <token>
 !gitea server logout[rm] <url or alias>

 !gitea whoami <url or alias>

==== Repository Alias

 !gitea ralias[r]
 !gitea ralias add[a] <alias> <repository>
 !gitea ralias remove[r, rm] <alias>
 !gitea ralias list[l, ls]

==== Issues

 !gitea issue[i]
 !gitea issue read[view, show] <url or alias> <repos or alias> <id>
 !gitea issue create <url or alias> <repos or alias> <title> <description>
 !gitea issue close <url or alias> <repos or alias> <id>
 !gitea issue reopen <url or alias> <repos or alias> <id>
 !gitea issue comment <url or alias> <repos or alias> <id> <comment text>
 !gitea issue comments[read-comments] <url or alias> <repos or alias> <id>
